baseURL = "https://pymis.netlify.com/"
languageCode = "en-us"
title = "CBA MIS Python Resources"
theme = "cupper-hugo-theme"

[[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2

[[menu.nav]]
    name = "Tags"
    url = "/tag/"
    weight = 3

[[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4

[[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
